apiVersion: v2
name: istio-system
description: A Helm chart for Istio
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
- name: base
  version: 1.19.1
  repository: https://istio-release.storage.googleapis.com/charts
