istiod:
  revision: 1-19-1

  revisionTags:
    - 'stable'
    - 'canary'

  sidecarInjectorWebhook:
    injectedAnnotations:
      ad.datadoghq.com/istio-proxy.logs: '[{"source":"envoy","env":"dev"}]'
  meshConfig:
    enablePrometheusMerge: false
    h2UpgradePolicy: UPGRADE
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      terminationDrainDuration: 45s
    defaultHttpRetryPolicy:
      attempts: 0
    accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS%
\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\"
\"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"

  global:
    caAddress: "cert-manager-istio-csr.cert-manager.svc:443"
    proxy:
      tracer: datadog
      excludeOutboundPorts: "5432"
    tracer:
      datadog:
        address: "datadog.datadog:8126"

  pilot:
    env:
      ISTIO_DEFAULT_REQUEST_TIMEOUT: "60s"
      ENABLE_CA_SERVER: false
      AUTO_RELOAD_PLUGIN_CERTS: true
    traceSampling: "10.0"
    autoscaleMin: 3
    autoscaleMax: 10
    cpu:
      targetAverageUtilization: 65
    tolerations:
    - key: "critical-workloads"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
