apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: istio-telemetry
  namespace: istio-system
spec:
  accessLogging:
  - providers:
    - name: envoy
    filter:
      expression: "response.code >= 400"
