{{- if .Values.externalSecretName -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cert-manager-secrets-store
    kind: SecretStore
  target:
    name: cert-manager-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecretName }}
{{- end }}
