apiVersion: v2
name: argocd
description: A Helm Chart to manage a ArgoCD 
type: application
version: 1.0.0

dependencies:
- name: argo-cd
  version: 5.46.8
  repository: https://argoproj.github.io/argo-helm

