# Using }}`}} to escape the templating used by appsets. 
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      {{- range $addon := .Values.addons }}
        - name: {{ regexReplaceAll "\\W+" $addon "-" }}
          path: {{ $addon }}
      {{- end }}
  template:
    metadata:
      name: '{{ `{{.name}}` }}'
      namespace: argocd
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - '../../clusters/{{ .Values.clusterName}}/addons-values.yaml'
            - '../../clusters/{{ .Values.clusterName }}/{{ `{{.path}}` }}/values.yaml'
          ignoreMissingValueFiles: true
        repoURL: '{{ .Values.repoUrl }}'
        path: 'charts/{{ `{{.path}}` }}'
        targetRevision: {{ .Values.targetRevision }} 
      destination:
        namespace: '{{ `{{.name}}` }}'
        name: 'in-cluster'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
